# Site Settings
title: Salman Shah - Blog
description: This is my technical blog where I'll be sharing insights to some of the projects that I have undertaken.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "salman-bhai.github.io" # the base hostname & protocol for your site, e.g. http://example.com

#User Settings
username: Salman Shah
user_description: "My life mantra: Eat, Sleep, Code Repeat :p" 
email: sbs.191197@gmail.com
github_username: salman-bhai
facebook_username: salman.shah.bhai

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
highlighter: rouge
permalink: /:title/

# SYntax Highlighting
syntax-highlighting:
  enabled : true

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false
